name: build-test

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  release:
    types: [published]  # ⇦ fire when you publish a GitHub Release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          check-latest: true

      - name: Remove hidden files
        run: find . -type f -name '.*' -not -name '.git' -not -name '.github' -exec rm -rf {} +

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install WPCS
        run: |
          composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require "wp-coding-standards/wpcs"
          composer global require "dealerdirect/phpcodesniffer-composer-installer"

      - name: Run WPCS
        run: |
          ~/.composer/vendor/bin/phpcs --standard=WordPress . --ignore=vendor,node_modules
        continue-on-error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout code (full history & tags)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js & PHP
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: |
          npm ci
          composer install --no-dev --optimize-autoloader

      - name: Build assets & generate POT
        run: |
          npm run dist

      - name: Create clean ZIP
        run: npm run dist

      - name: Extract ZIP to “dist/”
        run: |
          rm -rf dist
          mkdir dist
          unzip occidg.zip -d dist

      - name: Deploy to WP.org SVN
        # Pin to a known tag
        uses: 10up/action-wordpress-plugin-deploy@2.3.0
        with:
          # NOTE: no trailing slash
          svn-url:    https://plugins.svn.wordpress.org/occidg
          plugin-dir: dist
          assets-dir: assets
        env:
          SVN_USERNAME: ${{ secrets.WPORG_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WPORG_PASSWORD }}